config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks do
      patch :update_priority, on: :member
      patch :switch_done,     on: :member
    end
  end

  root 'projects#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :user
  has_many   :tasks, dependent: :delete_all
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :title,    presence: true
  validates :priority, inclusion: { in: [1, 2, 3, 4] }
  validates :done,     inclusion: { in: [true, false] }
  validate  :is_valid_deadline?

  belongs_to :project

  scope :by_priority, -> { order(:priority) }

  private

  def is_valid_deadline?
    if deadline && deadline < Date.today
      errors.add(:deadline, 'Should be a date in future or empty')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :validate_ownership!, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects
  end

  def show; end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      # redirect_to action: 'index'
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end

  def validate_ownership!
    redirect_to projects_path if @project.user != current_user
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task,
                only: [:edit, :update, :destroy, :update_priority, :switch_done]
  before_action :set_project,
                only: [:new, :edit, :update]
  before_action :validate_ownership!,
                only: [:edit, :update, :destroy, :update_priority, :switch_done]

  def new
    @task = @project.tasks.new
  end

  def create
    @task = Task.new(task_params)

    if @task.project.user != current_user
      # If user changes ProjectId manually
      # in order to add task to someone
      # just render 'new' page again
      render :new, status: :unauthorized
      return
    elsif @task.save
      redirect_to @task.project
    else
      render :new
    end
  end

  def edit; end

  def update
    if @project.user != current_user
      # Should be validated that user can't
      # change tasks in project where he's
      # not owner.
      render :edit, status: :unauthorized
      return
    elsif @task.update(task_params)
      redirect_to @task.project
    else
      render :edit
    end
  end

  def destroy
    @task.destroy

    redirect_to @task.project
  end

  def update_priority
    @task.update(priority: params[:priority])

    redirect_to @task.project
  end

  def switch_done
    @task.toggle!(:done)

    redirect_to @task.project
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:project_id, :title, :priority, :deadline, :done)
  end

  def validate_ownership!
    redirect_to projects_path if @task.project.user != current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= t('common.errors') %></h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TaskManager" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div id="email" class="btn btn-light btn-lg pull-right"><%= current_user.email %></div>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-light btn-lg pull-right' %>
      </nav>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/span-->
    </div><!--/row-->
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <%= render 'common/errors', resource: @project %>

  <div class="field">
    <%= f.label :title %>
    <br />
    <%= f.text_field :title %>
  </div>

  <br />
  <div class="actions">
    <%= f.submit "#{ @project.new_record? ? 'Create' : 'Change' }", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr>
  <td><%= project.title %></td>
  <td><%= link_to 'View', project_path(project) %></td>
  <td><%= link_to 'Edit', edit_project_path(project) %></td>
  <td><%= link_to 'Remove', [project], method: :delete, data: { confirm: 'Please confirm. Are you sure?' } %></td>
</tr>

app/views/projects/edit.html.erb
<h1>Change the Project</h1>

<%= render 'form' %>

<br />
<%= link_to 'Back', projects_path, class: 'btn btn-link' %>

app/views/projects/index.html.erb
<h1>Projects list</h1>

<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @projects %>
  </tbody>
</table>

<br>

<%= link_to 'Add new project', new_project_path, class: 'btn btn-primary btn-lg active' %>

app/views/projects/new.html.erb
<h1>Add project</h1>

<%= render 'form' %>

<br />
<%= link_to 'Back', projects_path, class: 'btn btn-link' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<% if @project.tasks.empty? %>
  <p>There's no Tasks in the Project.</p>
<% else %>
  <table class="table">
    <thead>
    <tr>
      <th width="200">Task</th>
      <th>Priority</th>
      <th>Deadline</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <%= render @project.tasks.by_priority %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Add new Task', new_project_task_path(@project), class: 'btn btn-primary btn-lg active' %>
<br />
<%= link_to 'Back', projects_path, class: 'btn btn-link' %>

app/views/tasks/_form.html.erb
<%= form_for [@task.project, @task] do |f| %>
  <%= render 'common/errors', resource: @task %>

  <div class="field">
    <%= f.label :project %><br>
    <%= f.collection_select :project_id, current_user.projects, :id, :title, {:selected => @task.project.id.to_s}%>
  </div>
  <br />

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <br />

  <div class="field">
    <%= f.label :priority %><br>
    <%= f.select :priority, [1,2,3,4] %>
  </div>
  <br />

  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_field :deadline, min: Date.today %>
  </div>
  <br />

  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done, class: 'form-check' %>
  </div>
  <br />

  <div class="actions">
    <%= f.submit "#{ @task.new_record? ? 'Create' : 'Change' }", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr>
  <td><%= task.title %></td>
  <td>
    <%= form_tag update_priority_project_task_path(task.project, task), method: :patch do %>
      <%= number_field_tag :priority, task.priority %>
      <%= submit_tag 'C' %>
    <% end %>
  </td>
  <td><%= task.deadline %></td>
  <td>
    <%= form_tag switch_done_project_task_path(task.project, task), method: :patch do %>
      <%= submit_tag (task.done ? 'Done' : 'Not done'), class: 'status btn btn-light' %>
    <% end %>
  </td>
  <td><%= link_to 'Edit', edit_project_task_path(task.project, task), class: 'btn btn-link' %></td>
  <td><%= link_to 'Remove', [task.project, task], method: :delete, data: { confirm: 'Please confirm. Are you sure?' }, class: 'btn btn-link'  %></td>
</tr>

app/views/tasks/edit.html.erb
<h1>Change the Task</h1>

<%= render 'form' %>

<br />
<%= link_to 'Back', projects_path, class: 'btn btn-link' %>

app/views/tasks/new.html.erb
<h1>Add task</h1>

<%= render 'form' %>

<br />
<%= link_to 'Back', projects_path, class: 'btn btn-link' %>